// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file mobilenetv2.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace mobilenetv2_demo
{
    
    public sealed class mobilenetv2Input
    {
        public ImageFeatureValue image; // BitmapPixelFormat: Rgba8, BitmapAlphaMode: Premultiplied, width: 224, height: 224
    }
    
    public sealed class mobilenetv2Output
    {
        public TensorString classLabel; // shape(-1,1)
        public IList<IDictionary<string,float>> classLabelProbs;
    }
    
    public sealed class mobilenetv2Model
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<mobilenetv2Model> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            mobilenetv2Model learningModel = new mobilenetv2Model();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<mobilenetv2Output> EvaluateAsync(mobilenetv2Input input)
        {
            binding.Bind("image", input.image);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new mobilenetv2Output();
            output.classLabel = result.Outputs["classLabel"] as TensorString;
            output.classLabelProbs = result.Outputs["classLabelProbs"] as IList<IDictionary<string,float>>;
            return output;
        }
    }
}

